Tweak the build wording a bit
Using boost >= 1.56.0 causes this error:

```
In file included from src/ripple_app/ledger/Ledger.h:33:0,
                from src/ripple_app/ledger/LedgerMaster.h:25,
                from src/ripple_overlay/impl/PeerImp.cpp:11:
src/ripple_app/tx/TransactionMeta.h: In member function 'bool ripple::TransactionMetaSet::hasDeliveredAmount() const':
src/ripple_app/tx/TransactionMeta.h:114:17: error: cannot convert 'const boost::optional<ripple::STAmount>' to 'bool' in return
         return mDelivered;
                ^
scons: *** [build/obj/src/ripple_overlay/impl/PeerImp.o] Error 1
scons: building terminated because of errors.
```

Given feedback from @syrenity and cross-checked in the commit history from http://savannah.gnu.org/bugs/?43198